#############################################################################
# Makefile for building: Gurobi
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  Gurobi.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Gurobi.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
MAKE          = make
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1y -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/gurobi/81/linux64/include -isystem /usr/local/include/jerasure
DEL_FILE      = rm -f
DEL_DIR       = rm -r
MKDIR_P       = mkdir -p
MOVE          = mv -f
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lgf_complete -lJerasure -L/opt/gurobi/81/linux64/lib/ -lgurobi_c++ -lgurobi81 

####### Output directory

OBJECTS_DIR   = build

####### Files

SOURCES       = main.cpp \
		utils/galois_stuff.cpp \
		utils/gurobi_stuff.cpp \
		utils/parameters.cpp \
		utils/solution.cpp \
		formulation/binary.cpp \
		formulation/combination.cpp \
		formulation/fullexclusive.cpp \
		formulation/formulation.cpp \
		formulation/exclusive.cpp \
		second_stage/secondstage.cpp \
		second_stage/descent.cpp \
		second_stage/dynamic.cpp \
		second_stage/ip.cpp 
OBJECTS       = main.o \
		solution.o \
		binary.o \
		combination.o \
		galois_stuff.o \
		gurobi_stuff.o \
		formulation.o \
		exclusive.o \
		secondstage.o \
		descent.o \
		dynamic.o \
		ip.o \
		parameters.o \
		fullexclusive.o
TARGET        = Gurobi

OBJS = $(patsubst %,$(OBJECTS_DIR)/%,$(OBJECTS))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJS) $(OBJCOMP) $(LIBS)

all: Makefile $(TARGET)

clean:
	-$(DEL_DIR) $(OBJECTS_DIR)
	-$(DEL_FILE) $(TARGET)
	-$(DEL_FILE) *~ core *.core

####### Compile

main.o: main.cpp formulation/formulation.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		second_stage/secondstage.h \
		utils/parameters.h \
		utils/cxxopts.hpp
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/main.o main.cpp

solution.o: utils/solution.cpp utils/solution.h \
		utils/parameters.h \
		utils/cxxopts.hpp \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/solution.o utils/solution.cpp

binary.o: formulation/binary.cpp formulation/binary.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		formulation/formulation.h \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/binary.o formulation/binary.cpp

combination.o: formulation/combination.cpp formulation/combination.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		formulation/formulation.h \
		utils/solution.h \
		utils/parameters.h \
		utils/cxxopts.hpp \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/combination.o formulation/combination.cpp

galois_stuff.o: utils/galois_stuff.cpp utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/galois_stuff.o utils/galois_stuff.cpp

gurobi_stuff.o: utils/gurobi_stuff.cpp /opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		utils/gurobi_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/gurobi_stuff.o utils/gurobi_stuff.cpp

formulation.o: formulation/formulation.cpp formulation/formulation.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		formulation/binary.h \
		formulation/exclusive.h \
		utils/gurobi_stuff.h \
		formulation/combination.h \
		utils/solution.h \
		utils/parameters.h \
		utils/cxxopts.hpp \
		formulation/fullexclusive.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/formulation.o formulation/formulation.cpp

exclusive.o: formulation/exclusive.cpp formulation/exclusive.h \
		utils/gurobi_stuff.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		formulation/formulation.h \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/exclusive.o formulation/exclusive.cpp

secondstage.o: second_stage/secondstage.cpp second_stage/secondstage.h \
		second_stage/descent.h \
		second_stage/dynamic.h \
		second_stage/ip.h \
		utils/gurobi_stuff.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/secondstage.o second_stage/secondstage.cpp

descent.o: second_stage/descent.cpp second_stage/descent.h \
		second_stage/secondstage.h \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/descent.o second_stage/descent.cpp

dynamic.o: second_stage/dynamic.cpp second_stage/dynamic.h \
		second_stage/secondstage.h \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/dynamic.o second_stage/dynamic.cpp

ip.o: second_stage/ip.cpp second_stage/ip.h \
		second_stage/secondstage.h \
		utils/gurobi_stuff.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/ip.o second_stage/ip.cpp

parameters.o: utils/parameters.cpp utils/parameters.h \
		utils/cxxopts.hpp
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/parameters.o utils/parameters.cpp

fullexclusive.o: formulation/fullexclusive.cpp formulation/fullexclusive.h \
		formulation/formulation.h \
		/opt/gurobi/81/linux64/include/gurobi_c++.h \
		/opt/gurobi/81/linux64/include/gurobi_c.h \
		utils/galois_stuff.h
	$(MKDIR_P) $(OBJECTS_DIR)
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJECTS_DIR)/fullexclusive.o formulation/fullexclusive.cpp
